controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\RegistForm;
use app\models\User;
use app\models\CheckinForm;

class SiteController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'users'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['users'],
                        'allow' => true,
                        'roles' => ['@'],
                    //'matchCallback' => function ($rule, $action) {
                    //    return User::isUserAdmin(Yii::$app->user->identity->username);
                    //      }
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ]
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {

        $regTable = RegistForm::find()->all();
        $model = new RegistForm();


// \yii\helpers\VarDumper::dump($model,10,1);// die();
// $model->save();
        if ($model->load(Yii::$app->request->post())) {

            if ($model->save(false)) {



//\yii\helpers\VarDumper::dump($model->name,10,1); die();
                Yii::$app->session->setFlash('success', 'Данные в БД записаны');
                return $this->refresh();
            } else {
// \yii\helpers\VarDumper::dump($model->getErrors());
                Yii::$app->session->setFlash('error', 'Ошибка');
            }
        }

        return $this->render('index', [
                    'regTable' => $regTable,
                    'model' => $model
                        ]
        );
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();

        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
                    'model' => $model
        ]);
    }

    public function actionDelete() {
        $model = Yii::$app->request->post('delete');
        if (isset($model)) {
            (RegistForm::deleteAll(['in', 'id', $model]));
            return $this->redirect(['index']);
        } else {
            echo 'Error';
        };

        $this->redirect(['index']);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout() {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact() {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
                    'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout() {

        return $this->render('about');
    }

    public function actionUsers() {
        $users = User::find('id', 'username', 'email')->all();
        //  \yii\helpers\VarDumper::dump($users);
        //  die;

        return $this->render('users', ['users' => $users,]);
    }

    public function actionCheck() {
        $model = new CheckinForm();

        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->checkin()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('check', [
                    'model' => $model,
        ]);
    }

}

views/site/about.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

</div>

views/site/check.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
 
$this->title = 'Регистрация';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-checkin">
    <h1><?= Html::encode($this->title) ?></h1>
    <p>Заполните все формы для регистрации:</p>
    <div class="row">
        <div class="col-lg-5">
 
            <?php $form = ActiveForm::begin(['id' => 'form-checkin']); ?>
                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>
                <?= $form->field($model, 'email') ?>
                <?= $form->field($model, 'password')->passwordInput() ?>
                <div class="form-group">
                    <?= Html::submitButton('Зарегистрироваться', ['class' => 'btn btn-primary', 'name' => 'checkin-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
 
        </div>
    </div>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

//use phpDocumentor\Reflection\Types\Boolean;
?>

<?php
/* @var $this yii\web\View */



$this->title = 'My Yii Application';
/* @var $regTable type */
//\yii\helpers\VarDumper::dump($reg, 10, true);
?>
<script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script>
    $(document).on("click", "#addForm", function () {
        var form = $("form[name='form']");
        form.css("display", "block");
        $("#addForm").replaceWith(form);

    });

    $(document).on("click", "#buttonDelete", function () {
        /* @var id integer */
        var id = $(this).attr('data-del');
        $("input[name='delete']").val(id);
        $("#formDelete").submit();
    });

</script> 



<div class="jumbotron">
    <table class="table table-striped">

        <?php foreach ($regTable as $r): ?>    
            <tr> 
                <td> <?php echo $r->id; ?>  <td>  
                <td> <?php echo $r->name; ?> <td>
                <td> <?php echo $r->email; ?> <td>
                <td> <?php echo $r->data; ?></td>
                <td> <?php echo $r->fm ? "Ж" : "М"; ?></td>
                <td> <?php //echo Html::a('Удалить', Url::to(['site/delete', 'id' => $r->id]))                     ?> </td>
                <td><button data-del="<?php echo $r->id ?>" id="buttonDelete" >Удалить</button></td>
                </td> 
            </tr>
        <?php endforeach; ?>
    </table>

    <form method = 'POST'  id="formDelete" action="<?php echo Url::to(['site/delete']) ?> " >
        <input type="hidden" name="_csrf" value="<?= Yii::$app->request->getCsrfToken() ?>" />
        <input type="hidden" name="delete" value='' />

    </form>

    <br>
    <button id="addForm" onclick="return false">Показать форму</button>
    <br>

    <?php
    $form = ActiveForm::begin(
                    ['options' => ['style' => "display: none",
                            'name' => "form"
                        ]]
            )
    ?>
    <?php echo $form->field($model, 'name')->label('Имя'); ?>
    <?php echo $form->field($model, 'email')->label('Почта'); ?>
    <?php echo $form->field($model, 'data')->label('Дата'); ?>
    <?php echo $form->field($model, 'fm')->radio(['label' => 'Ж', 'value' => 1, 'format' => 'boolean', 'uncheck' => null]); ?>
    <?php echo $form->field($model, 'fm')->radio(['label' => 'М', 'value' => 0, 'format' => 'boolean', 'uncheck' => null]); ?>
    <?php echo HTML::submitButton('Отправить') ?>
    <?php ActiveForm::end(); ?>
</div>

views/site/login.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php
    $form = ActiveForm::begin([
                'id' => 'login-form',
                'layout' => 'horizontal',
                'layout' => 'horizontal', 'fieldConfig' => [
                    'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
                    'labelOptions' => ['class' => 'col-lg-1 control-label'],
                ],
    ]);
    ?>

    <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <?=
    $form->field($model, 'rememberMe')->checkbox([
        'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
    ])
    ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/users.php
<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

use yii\helpers\Html;

$this->title = 'Пользователи';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

<table class="table table-striped">

        <?php foreach ($users as $user): ?>    
            <tr> 
                <td> <?php echo $user->id; ?>  <td>  
                <td> <?php echo $user->username; ?> <td>
                <td> <?php echo $user->email; ?> <td>
                
                
                </td> 
            </tr>
        <?php endforeach; ?>
    </table>


</div>